# Generated by Django 3.1 on 2020-08-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_auto_20200817_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uusername',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
