# Generated by Django 3.1 on 2020-08-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_auto_20200817_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='case_number',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
