# Generated by Django 3.1 on 2020-08-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0008_auto_20200817_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
