# Generated by Django 3.1 on 2020-08-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('secretary1', models.CharField(max_length=20)),
                ('secretary2', models.CharField(max_length=20)),
            ],
        ),
    ]
