# Generated by Django 3.1 on 2020-08-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0013_auto_20200819_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
