# Generated by Django 3.1 on 2020-08-19 06:29

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0014_auto_20200819_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
