# Generated by Django 3.1 on 2020-08-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0017_auto_20200819_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
