# Generated by Django 3.1 on 2020-08-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0018_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
