# Generated by Django 3.1 on 2020-08-20 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0019_auto_20200819_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VisitTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Secretary',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='visittime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.user'),
        ),
    ]
