# Generated by Django 3.1 on 2020-08-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0031_medicine_visittime_vtd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittime',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='reserve.user'),
        ),
        migrations.AlterField(
            model_name='visittime',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='reserve.user'),
        ),
    ]
