# Generated by Django 3.1 on 2020-08-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0032_auto_20200822_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visittime',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='visittime',
            name='empty',
            field=models.CharField(default='True ', max_length=20),
        ),
    ]
