# Generated by Django 3.1 on 2020-08-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0033_auto_20200823_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='visittime',
            name='full',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
