# Generated by Django 3.1 on 2020-08-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0035_auto_20200824_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sec1',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='sec2',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
